[[news]]
date = "27 червня 2025&nbsp;р."
lead = "Шановні коломияни!\r\n\r\nЦими вихідними наш театр вирушив у гастрольну подорож до Польщі в рамках спільного проєкту з Полтавським обласним академічним театром ім. М. Гоголя. Ми беремо участь у <span class=\"caps\">XV</span> Загальнопольських днях українського театру. \r\n\r\nТому на сцені невеличка пауза. \r\n\r\nУже наступного тижня обіцяємо повернутися з новими враженнями і, звісно, поділитися&nbsp;найцікавішим!"
title = "Коломийська трупа гастролює у Польщі"
url = "/news/item/58469"

[[news]]
date = "15 червня 2025&nbsp;р."
lead = "Блискучий тріумф Коломийського театру у Львові: &#8220;Моя земля залишиться зі мною, ми на чужині чужі&nbsp;люди&#8221;"
title = "Блискучий тріумф Коломийського театру у Львові: \"Моя земля залишиться зі мною, ми на чужині чужі люди\""
url = "/news/item/58468"

[[news]]
date = "20 травня 2025&nbsp;р."
lead = "Прем&#8217;єра зворушливої казки &#8220;Качечка-Крячечка&#8221; — вже цієї&nbsp;неділі!"
title = "Прем'єра зворушливої казки \"Качечка-Крячечка\" — вже цієї неділі!"
url = "/news/item/58467"

[[news]]
date = "13 травня 2025&nbsp;р."
lead = "<span class=\"dquo\">&#8220;</span>Коханці&#8221; – нова прем&#8217;єра у Коломийському&nbsp;театрі!"
title = "\"Коханці\" – нова прем'єра у Коломийському театрі!"
url = "/news/item/58466"

[[news]]
date = "22 квітня 2025&nbsp;р."
lead = "<span class=\"dquo\">&#8220;</span><span class=\"caps\">TABULA</span> <span class=\"caps\">RASA</span> / ЧИСТА ДОШКА&#8221; - на фестивалі &#8220;В гостях у Гоголя&#8221;&nbsp;2025"
title = "\"TABULA RASA / ЧИСТА ДОШКА\" - на фестивалі \"В гостях у Гоголя\" 2025"
url = "/news/item/58465"

[[news]]
date = "06 квітня 2025&nbsp;р."
lead = "«<span class=\"caps\">TABULA</span> <span class=\"caps\">RASA</span> / ЧИСТА ДОШКА» на гоголівській сцені: фестивальна вистава у&nbsp;Полтаві"
title = "«TABULA RASA / ЧИСТА ДОШКА» на гоголівській сцені: фестивальна вистава у Полтаві"
url = "/news/item/58464"

[[news]]
date = "28 березня 2025&nbsp;р."
lead = "«Цікаві люди». Дмитро Чиборак, директор Коломийського&nbsp;драмтеатру"
title = "«Цікаві люди». Дмитро Чиборак, директор Коломийського драмтеатру"
url = "/news/item/58463"
