[[news]]
date = "27 грудня 2025&nbsp;р."
lead = "Інший погляд: коли інклюзія стає&nbsp;мистецтвом"
title = "Інший погляд: коли інклюзія стає мистецтвом"
url = "/news/item/58474"

[[news]]
date = "16 грудня 2025&nbsp;р."
lead = "Інклюзивний театр «Ілюзія» представляє виставу «10 000&nbsp;ангелів»"
title = "Інклюзивний театр «Ілюзія» представляє виставу «10 000 ангелів»"
url = "/news/item/58473"

[[news]]
date = "07 жовтня 2025&nbsp;р."
lead = "Відкритий <span class=\"caps\">III</span> фестиваль української драматургії «Дніпро.Театр.<span class=\"caps\">UA</span>»"
title = "Відкритий III фестиваль української драматургії «Дніпро.Театр.UA»"
url = "/news/item/58472"

[[news]]
date = "31 липня 2025&nbsp;р."
lead = "Гастролі в Польщі очима тижневика &#8220;Наше&nbsp;слово&#8221;"
title = "Гастролі в Польщі очима тижневика \"Наше слово\""
url = "/news/item/58471"

[[news]]
date = "08 липня 2025&nbsp;р."
lead = "Грандіозне завершення театрального сезону: \r\nколомияни з полтавчанами повернулися із закордонних&nbsp;гастролей"
title = "Грандіозне завершення театрального сезону:  коломияни з полтавчанами повернулися із закордонних гастролей"
url = "/news/item/58470"

[[news]]
date = "27 червня 2025&nbsp;р."
lead = "Коломийська трупа гастролює у&nbsp;Польщі"
title = "Коломийська трупа гастролює у Польщі"
url = "/news/item/58469"

[[news]]
date = "15 червня 2025&nbsp;р."
lead = "Блискучий тріумф Коломийського театру у Львові: &#8220;Моя земля залишиться зі мною, ми на чужині чужі&nbsp;люди&#8221;"
title = "Блискучий тріумф Коломийського театру у Львові: \"Моя земля залишиться зі мною, ми на чужині чужі люди\""
url = "/news/item/58468"
