[[news]]
date = "25 серпня 2024&nbsp;р."
lead = "Напередодні Франкових роковин ми оживили на сцені сторінки драматичної долі нашого безсмертного&nbsp;Каменяра."
title = "«Тричі мені являлася любов…». Актори Коломийського театру потішили прем’єрою."
url = "/news/item/58454"

[[news]]
date = "14 серпня 2024&nbsp;р."
lead = "«Про що співає козак Мамай». Артисти Коломийського та Херсонського театрів презентували спільну&nbsp;постановку."
title = "Артисти Коломийського та Херсонського театрів презентували спільну постановку"
url = "/news/item/58452"

[[news]]
date = "02 липня 2024&nbsp;р."
lead = "<p><img class=\"news_lead\" src=\"/korg/kol/понад_120_дітей_коломийщини_взяли_участь_у_районному_святі_до_дня_захисту_дітей_small_index.jpg\"/>У розважальних заходах за участю аніматорів та перегляді вистави «Коза-Дереза» взяли участь понад 120 дітей, які проживають на території громад Коломийського&nbsp;району&#8230;</p>"
title = "Понад 120 дітей Коломийщини взяли участь у районному святі до Дня захисту дітей"
url = "/news/item/58451"

[[news]]
date = "17 грудня 2023&nbsp;р."
lead = "<span class=\"dquo\">&#8220;</span>Дві вистави - одна Україна&#8221;\r\nСпільний проєкт Коломийського академічного обласного українського драматичного театру імені І. Озаркевича і Полтавського академічного обласного українського музично-драматичного театру імені М. В.&nbsp;Гоголя"
title = "ХІІІ Всеукраїнський театральний фестиваль «Коломийські представлення», присвячений 175-річчю театру"
url = "/news/item/58453"

[[news]]
date = "12 жовтня 2021&nbsp;р."
lead = "<p><img class=\"news_lead\" src=\"/korg/kol/news/2021/58444/homo21-1-copy.jpg.pagespeed.ce.ja_jxdigpy_small_ix_crop.jpg\"/>10 жовтня у Миколаєві завершився  Міжнародний театральний фестиваль-конкурс Homo Ludens. Вистави оцінювали дві експертні&nbsp;ради&#8230;</p>"
title = "У Миколаєві назвали лауреатів Міжнародного театрального конкурсу Ноmo Ludens"
url = "/news/item/58444"

[[news]]
date = "04 жовтня 2021&nbsp;р."
lead = "<p><img class=\"news_lead\" src=\"/korg/kol/news/2021/58446/f9ea9e49eaf7f1b2b71217cc43da9828_small_ix_crop.jpg\"/>30 вересня 2021 року Коломийським академічним обласним українським драматичним театром ім.. І.Озаркевича на сцені Ладижинського сільського будинку&nbsp;культури&#8230;</p>"
title = "Озарківчани показали виставу \"СТО ТИСЯЧ\" у Ладижині"
url = "/news/item/58446"

[[news]]
date = "26 вересня 2021&nbsp;р."
lead = "<p><img class=\"news_lead\" src=\"/korg/kol/news/2021/58445/01008bkc-6984-1_small_ix_crop.jpg\"/>26 вересня у Кіровоградському обласному музично-драматичному театрі імені М.Л. Кропивницького відбулося закриття щорічного фестивалю “Вересневі&nbsp;самоцвіти”&#8230;</p>"
title = "Коломиський театр привіз нагороду з фестивалю \"Вересневі самоцвіти\""
url = "/news/item/58445"
