[[news]]
date = "27 січня 2025&nbsp;р."
lead = "Турбота про родину&nbsp;Героя"
title = "Турбота про родину Героя"
url = "/news/item/58461"

[[news]]
date = "24 січня 2025&nbsp;р."
lead = "Неймовірний день у Коломийському драмтеатрі: учні поринули у світ пригод на виставі «Тореадори з&nbsp;Васюківки»"
title = "Неймовірний день у Коломийському драмтеатрі: учні поринули у світ пригод на виставі «Тореадори з Васюківки»"
url = "/news/item/58460"

[[news]]
date = "18 січня 2025&nbsp;р."
lead = "Тореадори з Васюківки. У Коломийському театрі – прем’єра&nbsp;вистави"
title = "Тореадори з Васюківки. У Коломийському театрі – прем’єра вистави"
url = "/news/item/58458"

[[news]]
date = "14 січня 2025&nbsp;р."
lead = "Загубила дитину і 60 років провела у психлікарні | Чим вразить вистава “Табула раса” Коломийського&nbsp;театру"
title = "Загубила дитину і 60 років провела у психлікарні | Чим вразить вистава “Табула раса” Коломийського театру"
url = "/news/item/58457"

[[news]]
date = "23 грудня 2024&nbsp;р."
lead = "Прем’єра вистави &#8220;<span class=\"caps\">TABULA</span> <span class=\"caps\">RASA</span> / ЧИСТА ДОШКА&#8221; Коломийського театру: Незабутні&nbsp;враження!"
title = "Прем’єра вистави \"TABULA RASA / ЧИСТА ДОШКА\" Коломийського театру: Незабутні враження!"
url = "/news/item/58459"

[[news]]
date = "11 грудня 2024&nbsp;р."
lead = "Коломийський драмтеатр запрошує на&nbsp;прем&#8217;єру"
title = "Коломийський драмтеатр запрошує на прем'єру"
url = "/news/item/58456"

[[news]]
date = "29 жовтня 2024&nbsp;р."
lead = "На сцені Дніпровського національного академічного українського музично-драматичного театру імені Шевченка завершився Всеукраїнський мистецький фестиваль “Дніпро. Театр. <span class=\"caps\">UA</span>”."
title = "Озарківчани на фестивалі у Дніпрі"
url = "/news/item/58455"
