[[news]]
date = "07 жовтня 2025&nbsp;р."
lead = "Відкритий <span class=\"caps\">III</span> фестиваль української драматургії «Дніпро.Театр.<span class=\"caps\">UA</span>»"
title = "Відкритий III фестиваль української драматургії «Дніпро.Театр.UA»"
url = "/news/item/58472"

[[news]]
date = "31 липня 2025&nbsp;р."
lead = "Гастролі в Польщі очима тижневика &#8220;Наше&nbsp;слово&#8221;"
title = "Гастролі в Польщі очима тижневика \"Наше слово\""
url = "/news/item/58471"

[[news]]
date = "08 липня 2025&nbsp;р."
lead = "Грандіозне завершення театрального сезону: \r\nколомияни з полтавчанами повернулися із закордонних&nbsp;гастролей"
title = "Грандіозне завершення театрального сезону:  коломияни з полтавчанами повернулися із закордонних гастролей"
url = "/news/item/58470"

[[news]]
date = "27 червня 2025&nbsp;р."
lead = "Коломийська трупа гастролює у&nbsp;Польщі"
title = "Коломийська трупа гастролює у Польщі"
url = "/news/item/58469"

[[news]]
date = "15 червня 2025&nbsp;р."
lead = "Блискучий тріумф Коломийського театру у Львові: &#8220;Моя земля залишиться зі мною, ми на чужині чужі&nbsp;люди&#8221;"
title = "Блискучий тріумф Коломийського театру у Львові: \"Моя земля залишиться зі мною, ми на чужині чужі люди\""
url = "/news/item/58468"

[[news]]
date = "20 травня 2025&nbsp;р."
lead = "Прем&#8217;єра зворушливої казки &#8220;Качечка-Крячечка&#8221; — вже цієї&nbsp;неділі!"
title = "Прем'єра зворушливої казки \"Качечка-Крячечка\" — вже цієї неділі!"
url = "/news/item/58467"

[[news]]
date = "13 травня 2025&nbsp;р."
lead = "<span class=\"dquo\">&#8220;</span>Коханці&#8221; – нова прем&#8217;єра у Коломийському&nbsp;театрі!"
title = "\"Коханці\" – нова прем'єра у Коломийському театрі!"
url = "/news/item/58466"
