# This is a basic workflow to help you get started with Actions

name: test run generator

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: | 
          mkdir -pv pages |
          ls -ld data pages .
          
      - name: Resolve UID and GID
        run: |
         echo "UID=$( id -u ):$( id -g )" >> $GITHUB_ENV

      - name: Generate pages
        uses: addnab/docker-run-action@v3
        with:
          image: andriyg/pages-processor:0.0.8
          options: -v ${{ github.workspace }}:/pages --user=${{ env.UID }}   
          run: java -jar /pages-processor.jar
          

      - run: 
          set -x -e ;
          du -sh pages ;
          git status ;
          echo "Failure!" ;
          false

    